CREATE TABLE USERS (
  User_ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) NOT NULL UNIQUE,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Password_hash VARCHAR(255) NOT NULL,
  Created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE USERS
ADD Staff_ID INT UNIQUE,
ADD FOREIGN KEY (Staff_ID) REFERENCES STAFF(Staff_ID);
