CREATE TABLE PLACES (
  Customer_ID INT,
  Order_ID INT,
  PRIMARY KEY (Customer_ID, Order_ID),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID),
  FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID)
);

CREATE TABLE HOSTS (
  Event_ID INT,
  Order_ID INT,
  PRIMARY KEY (Event_ID, Order_ID),
  FOREIGN KEY (Event_ID) REFERENCES EVENTS(Event_ID),
  FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID)
);

CREATE TABLE CONTAIN (
  Order_ID INT,
  Item_ID INT,
  Quantity INT NOT NULL,
  Unit_price DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (Order_ID, Item_ID),
  FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID),
  FOREIGN KEY (Item_ID) REFERENCES MENU_ITEM(Item_ID)
);

CREATE TABLE FEATURES (
  Event_ID INT,
  Item_ID INT,
  PRIMARY KEY (Event_ID, Item_ID),
  FOREIGN KEY (Event_ID) REFERENCES EVENTS(Event_ID),
  FOREIGN KEY (Item_ID) REFERENCES MENU_ITEM(Item_ID)
);

CREATE TABLE USES (
  Event_ID INT,
  Inventory_ID INT,
  Qty_allocated DECIMAL(8,2),
  Qty_remaining DECIMAL(8,2),
  PRIMARY KEY (Event_ID, Inventory_ID),
  FOREIGN KEY (Event_ID) REFERENCES EVENTS(Event_ID),
  FOREIGN KEY (Inventory_ID) REFERENCES INVENTORY(Inventory_ID)
);

CREATE TABLE ASSIGNED_TO (
  Event_ID INT,
  Staff_ID INT,
  Shift VARCHAR(20),
  Duties VARCHAR(200),
  PRIMARY KEY (Event_ID, Staff_ID),
  FOREIGN KEY (Event_ID) REFERENCES EVENTS(Event_ID),
  FOREIGN KEY (Staff_ID) REFERENCES STAFF(Staff_ID)
);

CREATE TABLE ITEM_USES (
  Item_ID INT,
  Inventory_ID INT,
  Quantity_used DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (Item_ID, Inventory_ID),
  FOREIGN KEY (Item_ID) REFERENCES MENU_ITEM(Item_ID),
  FOREIGN KEY (Inventory_ID) REFERENCES INVENTORY(Inventory_ID)
);
